apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kuldeep-adwari23/GITOPS2026.git